[package]
name = "gentools"
version = "0.1.0"
edition = "2024"

[lib]
name = "genlib"
path = "src/lib.rs"

[[bin]]
name = "gen-ctl"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
bincode = "1.3.3"
ph = "0.10.0"
byteorder = "1.5.0"
clap = { version = "4.5.53", features = ["derive"] }
csv = "1.4.0"
glob = "0.3"
memmap2 = "0.9"
regex = "1.11"
rkyv = { version = "0.8.12" }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.8"
binout = "0.3.1"

[features]
default = ['opera']
opera = []
