name: CI

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
  release:
    types:
      - released
      - prereleased

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ${{ matrix.conf.os }}
    name: ${{ matrix.conf.os }}-${{ matrix.python-version }}-${{ matrix.conf.target-triple }}-${{ matrix.conf.target }}
    strategy:
      fail-fast: ${{ !( startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/tags/') ) }}
      matrix:
        python-version: 
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
          - '3.14t'
        conf:
          - { os: ubuntu-latest, target: x86_64,  target-triple: x86_64-unknown-linux-gnu,             manylinux: auto }
          - { os: ubuntu-latest, target: x86_64,  target-triple: x86_64-unknown-linux-musl,            manylinux: musllinux_1_1 }
          - { os: ubuntu-latest, target: aarch64, target-triple: aarch64-unknown-linux-gnu,            manylinux: auto }
          - { os: ubuntu-latest, target: aarch64, target-triple: aarch64-unknown-linux-musl,           manylinux: musllinux_1_1 }
          - { os: macos-15-intel, target: x86_64,     target-triple: x86_64-apple-darwin }
          - { os: macos-latest, target: aarch64,    target-triple: aarch64-apple-darwin }
          - { os: macos-latest, target: universal2, target-triple: x86_64-apple-darwin }
          - { os: windows-latest, target: x86_64, target-triple: x86_64-pc-windows-msvc, python-architecture: x64 }
          
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.conf.python-architecture }}
          allow-prereleases: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.conf.target-triple }}

      - name: Set MSVC developer prompt
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build wheel (OSX - Linux)
        if: runner.os != 'Windows'
        uses: PyO3/maturin-action@v1
        with:
          working-directory: rbufrp
          target: ${{ matrix.conf.target }}
          manylinux: ${{ matrix.conf.manylinux }}
          args: -i ${{ matrix.python-version }} --release --out dist

      - name: Build wheel (Windows)
        if: runner.os == 'Windows'
        working-directory: rbufrp
        run: |
          python -m pip install maturin delvewheel
          maturin build -i python --release --out wheels --target ${{ matrix.conf.target-triple }}
          $file = Get-ChildItem -Path "wheels" | Select-Object -First 1
          delvewheel repair -v "wheels\$($file.Name)" -w "dist"
    
      - name: Install built wheel and Test (Native)
        # TODO: I'm not sure but the actual collection of tests on windows using pypy3.10 takes forever and/or fails
        if: |
          !startsWith(matrix.conf.manylinux, 'musl') &&
          !( matrix.python-version == 'pypy3.10' && runner.os == 'Windows' ) &&
          ( matrix.conf.target == 'x86_64' || matrix.conf.target == 'universal2' )
        run: |
          python -m pip install rbufrp --pre --find-links rbufrp/dist --force-reinstall
          python -c "import rbufrp; print(rbufrp.__version__)"

      # Could use 'distro: alpine_latest' in 'run-on-arch-action' but seems difficult to install a specific version of python
      # so we'll just use existing python alpine images to test import and cli use w/o testing archs other than x86_64
      # - name: Install built wheel and Test (musllinux)
      #   # TODO: python:3.13-alpine doesn't exist yet
      #   if: startsWith(matrix.conf.manylinux, 'musl') && matrix.conf.target == 'x86_64' && !startsWith(matrix.python-version, '3.14')
      #   run: |
      #     docker run \
      #       -v $(pwd)/rbufrp/dist:/wheels \
      #       --rm python:${{ matrix.python-version }}-alpine sh \
      #         -c "pip install rbufrp --no-index --find-links /wheels && python -c 'import rbufrp'"

      # xref: https://github.com/milesgranger/cramjam/issues/194
      # - name: Install built wheel and Test (Cross)
      #   if: |
      #     !startsWith(matrix.conf.manylinux, 'musl') && 
      #     runner.os == 'Linux' &&
      #     contains(fromJson('["3.9", "3.11", "3.13"]'), matrix.python-version ) &&
      #     !startsWith(matrix.python-version, 'pypy')  &&
      #     contains(fromJson('["armv6", "armv7", "aarch64", "riscv64", "s390x", "ppc64le"]'), matrix.conf.target) 
      #   uses: uraimo/run-on-arch-action@v2
      #   with:
      #     arch: ${{ matrix.conf.target }}
      #     distro: ubuntu22.04
      #     githubToken: ${{ github.token }}
      #     # Mount the dist directory as /artifacts in the container
      #     dockerRunArgs: |
      #       --volume "${PWD}/dist:/artifacts"
      #     install: |
      #       apt-get update
      #       apt-get install -y --no-install-recommends python3 python3-venv software-properties-common
      #       add-apt-repository ppa:deadsnakes/ppa
      #       apt-get update
      #       apt-get install -y curl python${{ matrix.python-version }}-venv
      #     run: |
      #       ls -lrth /artifacts
      #       PYTHON=python${{ matrix.python-version }}
      #       $PYTHON -m venv venv
      #       venv/bin/pip install -U pip
      #       venv/bin/pip install rbufrp --pre --no-index --find-links /artifacts --force-reinstall
      #       venv/bin/python -c 'import rbufrp'

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        if: ${{ ( startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/tags/') ) }}
        with:
          name: ${{ matrix.conf.os }}-${{ matrix.python-version }}-${{ matrix.conf.target-triple }}-${{ matrix.conf.target }}
          path: rbufrp/dist


  build-sdist:
    name: Build sdists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Build sdist rbufrp
        working-directory: rbufrp
        run: |
          python -m pip install maturin
          maturin sdist --out dist
      - name: Upload sdists
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: rbufrp/dist

  gh-publish:
    name: Publish artifacts to GH
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: [build-test, build-sdist]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: .
        merge-multiple: true
    - name: List artifacts
      run: ls -lhs
    - name: Upload to GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: ./*

  pypi-publish:
    name: Upload release to Private PyPI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build-test, build-sdist]
    environment:
      name: pypi
    steps:
    - uses: actions/download-artifact@v4
      with:
        path: .
        merge-multiple: true
    - name: Move packages to clean directory
      run: |
        mkdir -p dist
        find . -name "*.whl" -exec mv {} dist/ \;
        find . -name "*.tar.gz" -exec mv {} dist/ \;
        rm -f dist/*wasm32.whl
        ls -lhs dist/
    - name: Publish package distributions to Private PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ secrets.PYPI_REPOSITORY_URL }}
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
        skip-existing: true
        packages-dir: ./dist
        verbose: true